// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package paymentmodels

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID                   int32
	CreatedAt            pgtype.Timestamptz
	Email                string
	Tier                 int32
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	UserID               pgtype.UUID
}
